#!/usr/bin/env python3
"""Static site generator. Produces HTML files in the _site/ directory."""

import os
import pathlib
import shutil

OUTPUT_DIR = pathlib.Path("_site")

STYLE = """\
:root { color-scheme: light dark; }
body {
    font-family: system-ui, sans-serif;
    max-width: 40rem;
    margin: 2rem auto;
    padding: 0 1rem;
    line-height: 1.6;
}
a { color: steelblue; }
"""


def page(title: str, body: str) -> str:
    """Wrap *body* HTML in a full page shell."""
    return (
        "<!doctype html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        f"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        f"  <title>{title}</title>\n"
        f"  <style>{STYLE}</style>\n"
        "</head>\n"
        "<body>\n"
        f"{body}\n"
        "</body>\n"
        "</html>\n"
    )


def build() -> None:
    OUTPUT_DIR.mkdir(exist_ok=True)

    index_html = page(
        "Home",
        "<h1>Welcome</h1>\n"
        "<p>This site is generated by Python and published with GitHub Pages.</p>\n"
        '<p><a href="kangourou/">Kangourou des Mathématiques — Jeu</a></p>',
    )
    (OUTPUT_DIR / "index.html").write_text(index_html)

    # Copy kangourou game if it has been generated
    kangourou_src = pathlib.Path("kangourou")
    if kangourou_src.is_dir():
        shutil.copytree(kangourou_src, OUTPUT_DIR / "kangourou", dirs_exist_ok=True)
        print("Copied kangourou/ game assets")

    print(f"Site built in {OUTPUT_DIR}/")


if __name__ == "__main__":
    build()
